/// Flutter icons Slot
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Slot
///      fonts:
///       - asset: fonts/Slot.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Slot {
  Slot._();

  static const _kFontFam = 'Slot';
  static const String? _kFontPkg = null;

  static const IconData cherry =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lucky7 =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
